server {
  listen 80;

  # Genera env.js dinámicamente con las variables de entorno
  location /env.js {
    default_type application/javascript;
    return 200 "window.__env = { API_URL: '${API_URL}' };";
  }

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri $uri/ /index.html;
  }
}
